[package]
name = "sakz"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
rand = "0.8.5"
resvg = "0.44.0"
svg = "0.18.0"
svg2pdf = "0.12.0"
tiny-skia = "0.11.4"
tiny-skia-path = "0.11.4"
usvg = "0.44.0"
