name: Release the package

on:
  release:
    types:
      - published

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release-to-crates-io:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Log in to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Build binaries in "release" mode
        run: cargo build -r

      - name: Publish to crates.io
        run: cargo publish

  release-to-pypi:
    needs: test
    uses: ./.github/workflows/release-python.yml
